### ISSUE TITLE
Did you train the tf Deit models from scratch? 

### ISSUE THREAD

**Issue by Kevinpsk** [sayakpaul/deit-tf#3]
Hi Sayak, 

Thanks a lot for sharing this tensorflow version of Deit models. 
I was wondering if you trained these tf Deit models from scratch to obtain the same level of accs as the original Pytorch Deit models? 
Have you tried to convert the original Pytorch model weights into tf format, and load them into your tf Deit model? Were you able to get the same level of acc as the pytorch model in this way? 
If you need to train these tf Deit models from scratch or fine tuning from the original pytorch weights, can you share your training or finetuning recipe as well? 
Thanks a lot for your help again.

**Comment by sayakpaul** [comment]
I converted the models. This is written in the README. 

Fine-tuning recipe is also available in this repository. Please consult the README.

**Comment by Kevinpsk** [comment]
Ok nice that you can get the same level of acc by converting the pytorch weights. I actually met some troubles achieving that, I will check details of your convert.py. 
Also Deit pytorch has a lot data augmentations, any plan to integrate those as well in here? 
Cheers

**Comment by sayakpaul** [comment]
I don't.
